git:
  depth: false
language: java
jdk: openjdk8
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.m2/wrapper"
    - "$HOME/.npm"
    - "$HOME/.sonar/cache"
    - "$HOME/.sonar/native-sonar-scanner"
# Change Travis install phase to only resolve dependencies needed to run the build.
# Otherwise it would run `mvn install`, which results in doing some Maven phases twice (validate, compile, jar, ...).
# https://docs.travis-ci.com/user/languages/java/#projects-using-maven
#
# We also want to avoid Maven's install phase to prevent from writing to ~/.m2/repository, which is cached.
install: mvn de.qaware.maven:go-offline-maven-plugin:1.2.1:resolve-dependencies -Prun-code-coverage,sonarcloud-analysis --quiet --show-version
# do not install to avoid dirtying the cache
script:
  - mvn verify -Prun-code-coverage -Dintegration-tests=true --show-version
  - mvn generate-resources -Psonarcloud-analysis
  # check that git working tree is clean after running npm install via a frontend-maven-plugin
  # the git command returns 1 and fails the build if there are any uncommitted changes
  - git diff HEAD --exit-code
after_success:
  - >
    if [ "$TRAVIS_EVENT_TYPE" == "push" ]; then
      docker login -u $DOCKER_USER -p $DOCKER_PASSWORD;
      export MODULE=standalone;
      export REPO=$DOCKER_REPO_PREFIX-$MODULE;
      export BRANCH=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`;
      export TAG=$BRANCH;
      export COMMIT_TAG=$TRAVIS_COMMIT
      echo "Building docker image $REPO:$TAG";
      docker build -f Dockerfile -t $REPO:$COMMIT_TAG .;
      docker tag $REPO:$COMMIT_TAG $REPO:$TAG;
      docker tag $REPO:$COMMIT_TAG $REPO:travis-$TRAVIS_BUILD_NUMBER;
      docker push $REPO;
    else 
      echo "Travis event type is $TRAVIS_EVENT_TYPE, not building docker image";
    fi

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl
  - echo $GCLOUD_SERVICE_KEY | base64 --decode -i > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
  - gcloud --quiet config set compute/zone asia-southeast1-a
  - gcloud --quiet config set project rostering-ai

deploy:
  - provider: script
    script: >-
      gcloud --quiet config set container/cluster ctrl-shift-standalone && 
      gcloud --quiet container clusters get-credentials ctrl-shift-standalone &&
      kubectl set image deployment/ctrl-shift-standalone ctrl-shift-standalone=$REPO:travis-$TRAVIS_BUILD_NUMBER
    skip_cleanup: true
    on:
      branch: $STAGING_BRANCH
      type: push
