git:
  depth: false
language: java
jdk: openjdk8
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.m2/wrapper"
    - "$HOME/.npm"
    - "$HOME/.sonar/cache"
    - "$HOME/.sonar/native-sonar-scanner"
# Change Travis install phase to only resolve dependencies needed to run the build.
# Otherwise it would run `mvn install`, which results in doing some Maven phases twice (validate, compile, jar, ...).
# https://docs.travis-ci.com/user/languages/java/#projects-using-maven
#
# We also want to avoid Maven's install phase to prevent from writing to ~/.m2/repository, which is cached.
install: mvn de.qaware.maven:go-offline-maven-plugin:1.2.1:resolve-dependencies -Pjacoco,sonar --quiet --show-version
# do not install to avoid dirtying the cache
script:
  - mvn verify -Pjacoco,sonar -Dintegration-tests=true --show-version
  # check that git working tree is clean after running npm install via a frontend-maven-plugin
  # the git command returns 1 and fails the build if there are any uncommitted changes
  - git diff HEAD --exit-code
after_success:
  - echo "On success, the working directory looks like..."
  - ls
  - cat .dockerignore
  - ls
  - cat Dockerfile
  - >
    if [ "$TRAVIS_EVENT_TYPE" == "push" ]; then
      docker login -u $DOCKER_USER -p $DOCKER_PASSWORD;
      export MODULE=standalone;
      export REPO=$DOCKER_REPO_PREFIX-$MODULE;
      export BRANCH=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`;
      export TAG=$BRANCH;
      export COMMIT_TAG=$TRAVIS_COMMIT
      echo "Building docker image $REPO:$TAG";
      docker build -f Dockerfile -t $REPO:$COMMIT_TAG .;
      docker tag $REPO:$COMMIT_TAG $REPO:$TAG;
      docker tag $REPO:$COMMIT_TAG $REPO:travis-$TRAVIS_BUILD_NUMBER;
      docker push $REPO;
    else 
      echo "Travis event type is $TRAVIS_EVENT_TYPE, not building docker image";
    fi
